#!/bin/sh

HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH="$HOME/.yarn/bin:$PATH"
export PATH="$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="$HOME/go/bin:$PATH"
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="/usr/local/bin:$PATH"
export VSCODE_USER="/Users/holmgmat/Library/Application Support/Code/User"

zsh_add_file "zsh-secrets"
zsh_add_file "zsh-lazy-load"

eval "$(zoxide init zsh)"

source "$PYENV_ROOT/versions/3.10.8/envs/neovim/bin/activate"
