#!/bin/sh


killport() { 
sudo kill -9 $(sudo fuser -n tcp $1 2> /dev/null);
}

# fuzzy search through aliases and run selected alias
fa() {
  local alias_name
  local selected_alias

  # If no arguments are provided, show all aliases
  if [ $# -eq 0 ]; then
    selected_alias=$(alias | fzf)
  else
    selected_alias=$(alias | grep $1 | fzf)
  fi

  # selected alias is run if exists
  if [ -n "$selected_alias" ]; then
    alias_name=$(echo "$selected_alias" | awk -F'[ =]' '{print $1}')
    
    # Prompt for arguments
    echo -e "Selected alias: $selected_alias\n"
    echo  "Supply args (press enter for no args): "
    read args

    if [ -n "$args" ]; then
      eval "$alias_name $args"
    else
      eval "$alias_name"
    fi
  fi
}

# nnn conf for tmux sess
# n() {
# 	if [ -n "$TMUX" ]; then
# 			nnn -ae $@
# 	else
# 			tmux new-session nnn -ae $@
# 	fi
# }

pathprepend() {
for ARG in "$@"
do
  while [[ $PATH =~ :$ARG: ]]
  do
    PATH=${PATH//:$ARG:/:}
  done
  PATH=${PATH#$ARG:}
  PATH=${PATH%:$ARG}
  export PATH=${ARG}:${PATH}
done
}

function cd {
    builtin cd "$@" && ls -laH
}

function awslogs {
  aws --profile beelab --region "$1" logs tail --follow "$2" 
}
