#!/bin/sh

# some useful options (man zshoptions)
setopt autocd extendedglob nomatch menucomplete
setopt interactive_comments
stty stop undef		# Disable ctrl-s to freeze terminal.
zle_highlight=('paste:none')

# beeping is annoying
unsetopt BEEP

# completions
autoload -Uz compinit
zstyle ':completion:*' menu select
# zstyle ':completion::complete:lsof:*' menu yes select
zmodload zsh/complist
compinit

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

# Colors
autoload -Uz colors && colors

# Useful Functions
source "$ZDOTDIR/zsh-utils"

# load custom executable functions
for function in $ZDOTDIR/functions/*; do
	local filename="${function#$ZDOTDIR/functions/}"
  zsh_add_file "functions/$filename" 
done

# Normal files to source
zsh_add_file "zsh-exports"
zsh_add_file "zsh-vim-mode"
zsh_add_file "zsh-aliases"
zsh_add_file "zsh-prompt"

# Append history instead of overwriting it
setopt APPEND_HISTORY

# Save the history after each command
setopt INC_APPEND_HISTORY

# Share the history among all shell instances
setopt SHARE_HISTORY

# Make new commands from other shells available to the current shell
fc -R


# Plugins
zsh_add_plugin "zsh-users/zsh-autosuggestions"
zsh_add_plugin "zsh-users/zsh-syntax-highlighting"
zsh_add_plugin "davidde/git"
zsh_add_plugin "johannchangpro/zsh-interactive-cd"
zsh_add_completion "esc/conda-zsh-completion" false
# For more plugins: https://github.com/unixorn/awesome-zsh-plugins
# More completions https://github.com/zsh-users/zsh-completions
#
# AWS cli completions
autoload bashcompinit && bashcompinit
complete -C '/usr/local/bin/aws_completer' aws

# Key-bindings
bindkey -s '^z' 'zi\n'
bindkey "^p" up-line-or-beginning-search # Up
bindkey "^n" down-line-or-beginning-search # Down

# FZF
source "$HOME/.fzf.zsh" 
# export FZF_DEFAULT_COMMAND='rg --hidden -l ""'

# Edit line in vim with ctrl-e:
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line
